[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pdf"
version = "0.1.0"
description = "Markdown to PDF converter"
authors = [{ name = "ezt" }]
requires-python = ">=3.8"
dependencies = []


[tool.setuptools.packages.find]
where = ["src"]
